### ISSUE TITLE
Error saving cats

### ISSUE THREAD

**Issue by mooijtech** [Thlumyn/clangen#8]
Hello,

I am getting the following error when attempting to save:
`AttributeError: 'str' object has no attribute 'ID'`

Due to this line: https://github.com/Thlumyn/clangen/blob/c0e1d6fa177950966811e45ec5ba671c9bf7c417/scripts/cats.py#L924

So somehow the "mentor" variable is getting assigned to a string, not the Cat object.

If you don't care about the saved data being human readable but only want to use it for saving/loading you could just dump the all_cats to disk via https://github.com/uqfoundation/dill (but the AttributeError still needs to be solved first).

Kind regards,
Marten Mooij

**Comment by Thlumyn** [comment]
I'd prefer for the saved data being readable; a lot of people are editing the save files to add custom cats and stuff
I think coffee is working on that bug here: https://github.com/Thlumyn/clangen/commit/37be2a3fb1d88157d97f71ac90c14beeb373fc38
Though that is keeping the mentor variable as a string (of just the mentor's ID)

**Comment by sedgestripe** [comment]
this should be fixed in https://github.com/Thlumyn/clangen/commit/93b2902a98503ab4f6d04415a94a6b049ce078a8

**Comment by mooijtech** [comment]
Thank you!
________________________________
